name: scanner

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

concurrency:
  group: scanner
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install aiohttp

      - run: python main.py

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          if [ -n "$(git status --porcelain)" ]; then
            git add result.txt store.json cache.json
            git commit -m "update"
            git push
          else
            echo "No changes"
          fi
